FROM node:20 AS build-stage

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build --prod

FROM nginx:alpine

# Create /etc/nginx/ssl directory (optional, but recommended)
RUN mkdir -p /etc/nginx/ssl

# Mount the directory containing certificates (adjust path)
VOLUME ["/home/gitrunner-ui"]

# Copy certificates from volume (if they exist)
COPY /home/gitrunner-ui/warriorit.site.crt /etc/nginx/ssl/warriorit.site.crt
COPY /home/gitrunner-ui/warriorit.site.key /etc/nginx/ssl/warriorit.site.key

COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=build-stage /app/dist/school-management1.1/browser /usr/share/nginx/html

EXPOSE 80

#docker build -t dom061077/sm-ui:1.0.1 -f path/to/your/Dockerfile .