FROM node:20 as build-stage

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build --prod

FROM nginx:alpine

# Create /etc/nginx/ssl directory (optional, but recommended)
RUN mkdir -p /etc/nginx/ssl

# Check for certificate existence on host VPS (using shell scripting)
COPY --from=0 /home/gitrunner-ui/warriorit.site.crt /etc/nginx/ssl/warriorit.site.crt 
COPY --from=0 /home/gitrunner-ui/warriorit.site.key /etc/nginx/ssl/warriorit.site.key


COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=build-stage /app/dist/school-management1.1/browser /usr/share/nginx/html

EXPOSE 80

#docker build -t dom061077/sm-ui:1.0.1 -f path_to_Dockerfile .