name: Schoolmanagement UI

on:
  push:
    branches:
      - master
#    paths:
#      - book-network-ui/**
#      - docker/frontend/**
#      - 'docker-compose.yml'
#      - .github/workflows/*-frontend.yml
jobs:
  build-image:
    name: Build FE Docker image
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract project version
        id: extract_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      
      - name: Copy certificates from VPS
        run: |
          scp  ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:/home/gitrunner-ui/warriorit.site.crt ./warriorit.site.crt
          scp  ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:/home/gitrunner-ui/warriorit.site.key ./warriorit.site.key

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sm-ui:latest,${{ secrets.DOCKERHUB_USERNAME }}/sm-ui:${{ steps.extract_version.outputs.VERSION }}

#  health-check:
#    name: UI Health Check
#    runs-on: self-hosted
#    needs: [deploy]
#    steps:
#      - name: Check the docker container health status
#        run: |
#          if ! docker ps -a | grep bsn-ui; then
#            echo "Container is not running"
#            exit 1
#          fi
